### ISSUE TITLE
Error: spawn: open ENOENT

### ISSUE THREAD

**Issue by MaartenvanSpil** [SC5/sc5-styleguide-visualtest#11]
I get the following error when running the visual test, though making the grid screenshots goes ok.

``` javascript
[08:14:47] Starting 'visual:test'...
PhantomJS is launching GhostDriver...
[INFO  - 2015-11-11T07:14:48.371Z] GhostDriver - Main - running on port 4444
[INFO  - 2015-11-11T07:14:50.027Z] Session [e58f0550-8843-11e5-be9e-eb7e6baf020a] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34","webSecurityEnabled":true}
[INFO  - 2015-11-11T07:14:50.027Z] Session [e58f0550-8843-11e5-be9e-eb7e6baf020a] - page.customHeaders:  - {}
[INFO  - 2015-11-11T07:14:50.027Z] Session [e58f0550-8843-11e5-be9e-eb7e6baf020a] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"1.9.8","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"windows-8-32bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2015-11-11T07:14:50.027Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: e58f0550-8843-11e5-be9e-eb7e6baf020a
✓ 1.1 plain [chrome]
✓ 1.2 plain [chrome]
✓ 1.3.1 plain [chrome]
✓ 1.3.2 plain [chrome]
✓ 1.4 plain [chrome]
✓ 2 plain [chrome]
✓ 3.1 plain [chrome]
Total: 7 Passed: 7 Failed: 0 Skipped: 0
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn open ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

**Comment by MaartenvanSpil** [comment]
Used this script:

``` javascript
(function() {
    var childProcess = require("child_process");
    var oldSpawn = childProcess.spawn;
    function mySpawn() {
        console.log('spawn called');
        console.log(arguments);
        var result = oldSpawn.apply(this, arguments);
        return result;
    }
    childProcess.spawn = mySpawn;
})();
```

To find out this:

``` javascript
spawn called
{ '0': 'open', '1': [ 'gemini-report/index.html' ] }
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn open ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

**Comment by varya** [comment]
Hi Maarten! I'll try to look at it when I have time. But maybe not very soon, sorry. If you fix it yourself or someone would help you, could you share the result here?

**Comment by varya** [comment]
Also, write please which node and npm version you have.

**Comment by MaartenvanSpil** [comment]
Hi Varya, thanks in advance!

Node: v0.12.2
NPM: 2.7.4

**Comment by MaartenvanSpil** [comment]
Updated my Node to v5.1.0 and my npm to v5.1.0 but still not working. 
It just won't generate index.html in the gemini-report folder, so it cannot open it.
